version: '3.8'
services:
  frontend:
    image: frontend
    depends_on:
      - backend
    build: 
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - 80:80
  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: ./src/main/docker/Dockerfile.multi
    ports:
    - 8080:8080